name: Release PDF

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SITE_NAME: Lichtara
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci --no-audit --no-fund

      - name: Build
        run: npm run build

      - name: Generate PDF and image
        run: npm run pdf

      - name: Archive dist
        run: |
          echo "Preparing release artifacts"
          ls -la dist

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload PDF asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/contrato-do-sim.pdf
          asset_name: contrato-do-sim.pdf
          asset_content_type: application/pdf

      - name: Upload PNG insignia
        if: ${{ hashFiles('dist/assets/insignia.png') != '' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/assets/insignia.png
          asset_name: insignia.png
          asset_content_type: image/png
