name: Secret Scan
on:
  push:
    branches: [ main, cleaned-*, feature/** ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
        with:
          version: latest
          args: detect --verbose --redact --source . --config .gitleaks.toml
